import '@/globals.css';
import Header from '@components/Header';
import Nav from '@common/Nav';
import { ProviderAuth } from '@contexts/AuthContext';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <ProviderAuth>
      <html lang="en">
        <body className={inter.className}>
          <div className="min-h-full">
            <Header />
            <Nav />
            <main>
              <div className="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
                {children}
              </div>
            </main>
          </div>
        </body>
      </html>
    </ProviderAuth>
  );
}
